#!/usr/bin/env bash

color_off="\033[0m"
color_error="\033[0;31m"

commit_msg="$(cat $1)"
commit_types="feat|fix|config|docs|style|refactor|test|chore|perf|other"

msg_regex="^(${commit_types})(\((.*)\))?:"

printf "\033[0;35m⠹\033[0m Checking commit message..."

if [[ ! $commit_msg =~ $msg_regex ]]; then
  printf "\r\033[0;31m❯\033[0m Checking commit message...\n"
  printf "  \033[0;31m✖ Proper commit message format is required\033[0m"
  printf " \033[1;30m[FAILED]\033[0m\n"
  exit 1
fi

printf "\r\033[0;32m✔\033[0m Checking commit message...\n"
